### ISSUE TITLE
Single Server Deployment

### ISSUE THREAD

**Issue by HuiJun** [Open-MBEE/mms5-deployment#8]
We need a single server deployment using docker-compose along with documentation on how to utilize it.

The single server deployment should not include the auth-service, as it currently requires an LDAP service provider to function. Because of this, we will need to include documentation on how to send authentication to layer1-service. Additionally, we will also exclude the store-service, since functionality with minio has yet to be tested and verified.

**Comment by dlamoris** [comment]
there is an open ldap docker https://hub.docker.com/r/bitnami/openldap/, let's try and get a docker compose that includes all components to serve as an semi complete example deployment (minio and store service would be great to have working, but ok if not)
